# BoardConfig.mk for SmartPi One (Allwinner H3)
# Based on GloDroid configuration for sun8i-h3

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

# Board
TARGET_BOARD_PLATFORM := sun8i
TARGET_BOOTLOADER_BOARD_NAME := smartpi1
TARGET_NO_BOOTLOADER := false
TARGET_NO_RADIOIMAGE := true

# Kernel
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_KERNEL_CMDLINE := console=ttyS0,115200 earlyprintk root=/dev/mmcblk0p2 rootwait
BOARD_KERNEL_IMAGE_NAME := zImage
TARGET_KERNEL_SOURCE := kernel/allwinner/h3
TARGET_KERNEL_CONFIG := smartpi1_defconfig

# Device Tree
BOARD_KERNEL_SEPARATED_DT := true
BOARD_DTBO_CFG := $(DEVICE_PATH)/dtbo.cfg

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 20971520
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_VENDORIMAGE_PARTITION_SIZE := 134217728
BOARD_USERDATAIMAGE_PARTITION_SIZE := 268435456
BOARD_FLASH_BLOCK_SIZE := 4096

# Filesystem
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_COPY_OUT_VENDOR := vendor

# Graphics - Using open-source Lima driver (no proprietary blobs needed)
BOARD_GPU_TYPE := mali400
USE_OPENGL_RENDERER := true
TARGET_USES_HWC2 := true
BOARD_USES_LIBDRM := true

# Mesa/Lima GPU (open-source driver for Mali400)
BOARD_MESA3D_USES_MESON_BUILD := true
BOARD_MESA3D_GALLIUM_DRIVERS := lima
BOARD_MESA3D_VULKAN_DRIVERS :=
BOARD_GPU_DRIVERS := lima

# DRM HWComposer
BOARD_USES_DRM_HWCOMPOSER := true
BOARD_DRM_HWCOMPOSER_BUFFER_IMPORTER := minigbm

# Audio
BOARD_USES_ALSA_AUDIO := true
BOARD_USES_TINY_ALSA_AUDIO := true

# WiFi
BOARD_WLAN_DEVICE := xradio
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth

# Display
TARGET_SCREEN_DENSITY := 160
TARGET_SCREEN_WIDTH := 1920
TARGET_SCREEN_HEIGHT := 1080

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/fstab.smartpi1
BOARD_INCLUDE_RECOVERY_DTBO := true

# SELinux
BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy

# VNDK
BOARD_VNDK_VERSION := current

# Treble
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
PRODUCT_FULL_TREBLE_OVERRIDE := true

# Verified Boot
BOARD_AVB_ENABLE := false

# OTA
AB_OTA_UPDATER := false
